import { apiRequest } from './client.js'

const json = (method, body = {}) => ({ method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) })
const root = (projectUuid, suffix = '') => `/api/v1/projects/${encodeURIComponent(projectUuid)}${suffix}`
const chapterRoot = (projectUuid, chapterUuid, suffix = '') => root(projectUuid, `/chapters/${encodeURIComponent(chapterUuid)}${suffix}`)
const sectionRoot = (projectUuid, chapterUuid, sectionUuid, suffix = '') => chapterRoot(projectUuid, chapterUuid, `/comic-sections/${encodeURIComponent(sectionUuid)}${suffix}`)

export const getPremise = (projectUuid) => apiRequest(root(projectUuid, '/premise'))
export const updatePremise = (projectUuid, payload) => apiRequest(root(projectUuid, '/premise'), json('PATCH', payload))
export const listPremiseSources = (projectUuid, { page = 1, perPage = 20 } = {}) => apiRequest(root(projectUuid, `/premise-sources?${new URLSearchParams({ page: String(page), per_page: String(perPage) })}`))
export const createPremiseSource = (projectUuid, payload) => apiRequest(root(projectUuid, '/premise-sources'), json('POST', payload))
export const updatePremiseSource = (projectUuid, sourceUuid, payload) => apiRequest(root(projectUuid, `/premise-sources/${encodeURIComponent(sourceUuid)}`), json('PATCH', payload))
export const generateSettingImage = (projectUuid, sourceUuid, payload) => apiRequest(root(projectUuid, `/premise-sources/${encodeURIComponent(sourceUuid)}/setting-generations`), json('POST', payload))
export const listSettingImages = (projectUuid, { sourceUuids = [] } = {}) => {
  const search = new URLSearchParams()
  sourceUuids.forEach((sourceUuid) => search.append('source_uuid', sourceUuid))
  const suffix = search.size ? `?${search}` : ''
  return apiRequest(root(projectUuid, `/premise-setting-images${suffix}`))
}
export const importSettingImage = (projectUuid, payload) => apiRequest(root(projectUuid, '/premise-setting-images'), json('POST', payload))
export const selectSettingImage = (projectUuid, settingUuid) => apiRequest(root(projectUuid, `/premise-setting-images/${encodeURIComponent(settingUuid)}/selections`), json('POST'))
export const breakdownSettingImage = (projectUuid, settingUuid, payload) => apiRequest(root(projectUuid, `/premise-setting-images/${encodeURIComponent(settingUuid)}/breakdowns`), json('POST', payload))
export const listPremiseAssets = (projectUuid, { tag = '', state = 'active' } = {}) => apiRequest(root(projectUuid, `/premise-assets?${new URLSearchParams({ tag, state })}`))
export const getPremiseAsset = (projectUuid, assetUuid) => apiRequest(root(projectUuid, `/premise-assets/${encodeURIComponent(assetUuid)}`))
export const createPremiseAsset = (projectUuid, payload) => apiRequest(root(projectUuid, '/premise-assets'), json('POST', payload))
export const updatePremiseAsset = (projectUuid, assetUuid, payload) => apiRequest(root(projectUuid, `/premise-assets/${encodeURIComponent(assetUuid)}`), json('PATCH', payload))
export const trashPremiseAsset = (projectUuid, assetUuid, revision) => apiRequest(root(projectUuid, `/premise-assets/${encodeURIComponent(assetUuid)}?expected_revision=${encodeURIComponent(revision)}`), { method: 'DELETE' })
export const restorePremiseAsset = (projectUuid, assetUuid, revision) => apiRequest(root(projectUuid, `/premise-assets/${encodeURIComponent(assetUuid)}/restorations`), json('POST', { expected_revision: revision }))
export const permanentlyDeletePremiseAsset = (projectUuid, assetUuid, revision) => apiRequest(root(projectUuid, `/premise-assets/${encodeURIComponent(assetUuid)}/permanent?expected_revision=${encodeURIComponent(revision)}`), { method: 'DELETE' })
export const emptyPremiseAssetTrash = (projectUuid) => apiRequest(root(projectUuid, '/premise-assets/trash'), { method: 'DELETE' })
export const listPremiseAssetVariants = (projectUuid, assetUuid) => apiRequest(root(projectUuid, `/premise-assets/${encodeURIComponent(assetUuid)}/variants`))
export const createPremiseAssetVariant = (projectUuid, assetUuid, payload) => apiRequest(root(projectUuid, `/premise-assets/${encodeURIComponent(assetUuid)}/variants`), json('POST', payload))
export const selectPremiseAssetVariant = (projectUuid, assetUuid, variantUuid, revision) => apiRequest(root(projectUuid, `/premise-assets/${encodeURIComponent(assetUuid)}/variants/${encodeURIComponent(variantUuid)}/selections`), json('POST', { expected_revision: revision }))
export const generatePremiseAssetVariant = (projectUuid, assetUuid, payload) => apiRequest(root(projectUuid, `/premise-assets/${encodeURIComponent(assetUuid)}/generations`), json('POST', payload))

export const getComicState = (projectUuid, chapterUuid) => apiRequest(chapterRoot(projectUuid, chapterUuid, '/comic'))
export const listComicSections = (projectUuid, chapterUuid) => apiRequest(chapterRoot(projectUuid, chapterUuid, '/comic-sections'))
export const createComicSection = (projectUuid, chapterUuid, payload) => apiRequest(chapterRoot(projectUuid, chapterUuid, '/comic-sections'), json('POST', payload))
export const updateComicSection = (projectUuid, chapterUuid, sectionUuid, payload) => apiRequest(sectionRoot(projectUuid, chapterUuid, sectionUuid), json('PATCH', payload))
export const deleteComicSection = (projectUuid, chapterUuid, sectionUuid, revision) => apiRequest(`${sectionRoot(projectUuid, chapterUuid, sectionUuid)}?expected_revision=${encodeURIComponent(revision)}`, { method: 'DELETE' })
export const reorderComicSections = (projectUuid, chapterUuid, sectionUuids) => apiRequest(chapterRoot(projectUuid, chapterUuid, '/comic-section-order'), json('PUT', { section_uuids: sectionUuids }))
export const setComicSectionPremiseAssets = (projectUuid, chapterUuid, sectionUuid, premiseAssetUuids, revision) => apiRequest(sectionRoot(projectUuid, chapterUuid, sectionUuid, '/premise-assets'), json('PUT', { premise_asset_uuids: premiseAssetUuids, expected_revision: revision }))
export const listStoryboards = (projectUuid, chapterUuid, sectionUuid) => apiRequest(sectionRoot(projectUuid, chapterUuid, sectionUuid, '/storyboard-variants'))
export const createStoryboard = (projectUuid, chapterUuid, sectionUuid, payload) => apiRequest(sectionRoot(projectUuid, chapterUuid, sectionUuid, '/storyboard-variants'), json('POST', payload))
export const selectStoryboard = (projectUuid, chapterUuid, sectionUuid, variantUuid, revision) => apiRequest(sectionRoot(projectUuid, chapterUuid, sectionUuid, `/storyboard-variants/${encodeURIComponent(variantUuid)}/selections`), json('POST', { expected_revision: revision }))
export const importSectionImage = (projectUuid, chapterUuid, sectionUuid, payload) => apiRequest(sectionRoot(projectUuid, chapterUuid, sectionUuid, '/images'), json('POST', payload))
export const listImageVariants = (projectUuid, chapterUuid, sectionUuid) => apiRequest(sectionRoot(projectUuid, chapterUuid, sectionUuid, '/image-variants'))
export const selectImageVariant = (projectUuid, chapterUuid, sectionUuid, variantUuid, revision) => apiRequest(sectionRoot(projectUuid, chapterUuid, sectionUuid, `/image-variants/${encodeURIComponent(variantUuid)}/selections`), json('POST', { expected_revision: revision }))
export const generateSectionImage = (projectUuid, chapterUuid, sectionUuid, payload) => apiRequest(sectionRoot(projectUuid, chapterUuid, sectionUuid, '/image-generations'), json('POST', payload))
export const generateChapterImagesBatch = (projectUuid, chapterUuid, payload) => apiRequest(chapterRoot(projectUuid, chapterUuid, '/comic-image-generation-batches'), json('POST', payload))
export const listComicSnapshots = (projectUuid, chapterUuid) => apiRequest(chapterRoot(projectUuid, chapterUuid, '/comic-snapshots'))
export const getComicSnapshot = (projectUuid, chapterUuid, snapshotUuid) => apiRequest(chapterRoot(projectUuid, chapterUuid, `/comic-snapshots/${encodeURIComponent(snapshotUuid)}`))
export const restoreComicSnapshot = (projectUuid, chapterUuid, snapshotUuid) => apiRequest(chapterRoot(projectUuid, chapterUuid, `/comic-snapshots/${encodeURIComponent(snapshotUuid)}/restorations`), json('POST'))
export const listComicExports = (projectUuid, { page = 1, perPage = 20, scope = '', chapterUuid = '', taskUuid = '', snapshotHash = '', format = '', status = '' } = {}) => {
  const search = new URLSearchParams({ page: String(page), per_page: String(perPage) })
  if (scope) search.set('scope', scope)
  if (chapterUuid) search.set('chapter_uuid', chapterUuid)
  if (taskUuid) search.set('task_uuid', taskUuid)
  if (snapshotHash) search.set('snapshot_hash', snapshotHash)
  if (format) search.set('format', format)
  if (status) search.set('status', status)
  return apiRequest(root(projectUuid, `/comic-exports?${search}`))
}
export const getComicExportReadiness = (projectUuid, { scope, chapterUuid = '' }) => apiRequest(root(projectUuid, `/comic-exports/readiness?${new URLSearchParams({ scope, chapter_uuid: chapterUuid })}`))
export const createComicExport = (projectUuid, payload) => apiRequest(root(projectUuid, '/comic-exports'), json('POST', payload))
export const listProductionTasks = (projectUuid, limit = 100) => apiRequest(root(projectUuid, `/production-tasks?limit=${encodeURIComponent(limit)}`))
export const getProductionTask = (projectUuid, taskUuid) => apiRequest(root(projectUuid, `/production-tasks/${encodeURIComponent(taskUuid)}`))
export const listProductionTaskEvents = (projectUuid, taskUuid, query = {}) => apiRequest(root(projectUuid, `/production-tasks/${encodeURIComponent(taskUuid)}/events?${new URLSearchParams(query)}`))
export const cancelProductionTask = (projectUuid, taskUuid) => apiRequest(root(projectUuid, `/production-tasks/${encodeURIComponent(taskUuid)}/cancellations`), json('POST'))
export const retryProductionTask = (projectUuid, taskUuid) => apiRequest(root(projectUuid, `/production-tasks/${encodeURIComponent(taskUuid)}/retries`), json('POST'))
