import assert from 'node:assert/strict'
import test from 'node:test'
import { readFileSync } from 'node:fs'

import { projectCoverSource, projectRowActions, projectRowPrimaryAction } from './projectIndexState.js'

test('unavailable local projects stay recoverable without an open action', () => {
	assert.deepEqual(projectRowActions({ open: false, available: false }), ['relocate', 'forget'])
})

test('active and recent project rows expose the correct local actions', () => {
	assert.deepEqual(projectRowActions({ open: true, available: true }), ['enter', 'reveal', 'forget'])
	assert.deepEqual(projectRowActions({ open: false, available: true, status: 'recent' }), ['enter', 'reveal', 'relocate', 'forget'])
})

test('project rows use the available action that enters the workspace', () => {
	assert.equal(projectRowPrimaryAction({ open: true, available: true }), 'enter')
	assert.equal(projectRowPrimaryAction({ open: false, available: true }), 'enter')
	assert.equal(projectRowPrimaryAction({ open: false, available: false }), null)
})

test('project covers preserve backend content versions and retain the empty fallback', () => {
  const versionedURL = '/media/recent-projects/019-project/cover?v=0123456789abcdef'
  assert.equal(projectCoverSource({ cover_image_url: versionedURL }), versionedURL)
  assert.equal(projectCoverSource({ cover_image_url: '' }), '/favicon.png')
  assert.equal(projectCoverSource(null), '/favicon.png')
})

test('recent projects render picture-book covers with secondary details in the more menu', () => {
  const source = readFileSync(new URL('./HomePage.jsx', import.meta.url), 'utf8')
  const menuSource = readFileSync(new URL('../components/ProjectActionsMenu.jsx', import.meta.url), 'utf8')
  const styles = readFileSync(new URL('../styles/projects.sass', import.meta.url), 'utf8')
  assert.match(source, /className="project-card-grid" role="list"/)
  assert.match(source, /className=\{`project-card \$\{onActivate/)
  assert.match(source, /className=\{`project-card__cover \$\{project\.cover_image_url/)
  assert.match(source, /src=\{projectCoverSource\(project\)\}/)
  assert.match(source, /<ProjectActionsMenu actions=\{actions\}/)
  assert.match(menuSource, /project-index-menu__path/)
  assert.doesNotMatch(source, /project-index-table/)
  assert.match(styles, /\.project-card-grid[\s\S]*grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/)
  assert.match(styles, /\.project-card__cover\n[\s\S]*?  aspect-ratio: 4 \/ 3[\s\S]*?\n  img\n    width: 100%\n    height: 100%\n    min-height: 0\n    display: block\n    object-fit: contain/)
  assert.match(styles, /@media \(max-width: 760px\)[\s\S]*?\.project-card-grid[\s\S]*?grid-template-columns: 1fr/)
})

test('project page presents creation, open, relocation and forget dialogs', () => {
  const source = readFileSync(new URL('./HomePage.jsx', import.meta.url), 'utf8')
  const menuSource = readFileSync(new URL('../components/ProjectActionsMenu.jsx', import.meta.url), 'utf8')
  for (const dialog of ["dialog === 'create'", "dialog === 'open'", "dialog === 'relocate'", "dialog === 'forget'"]) {
    assert.match(source, new RegExp(dialog.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')))
  }
  assert.match(source, /projects\.forget\.hint/)
  assert.match(source, /queryKey: \['project-defaults'\], queryFn: getProjectDefaults/)
  assert.match(source, /if \(!parentPathDirty && defaultProjectParentPath\) setParentPath\(defaultProjectParentPath\)/)
  assert.match(source, /setParentPath\(defaultProjectParentPath\)[\s\S]*setParentPathDirty\(false\)/)
  assert.doesNotMatch(source, /disabled=\{[^}]*projectDefaultsQuery\.isError/)
  assert.doesNotMatch(source, /~\/Documents\/Lumi|\/Users\/me\//)
  assert.match(source, /projects\.dialog\.open\.title/)
  assert.match(source, /searchParams\.get\('create_project'\) !== '1'/)
  assert.match(source, /nextSearchParams\.delete\('create_project'\)/)
  assert.match(source, /selectDirectoryMutation\.mutate\(existingPath\)/)
  assert.match(source, /projects\.open\.choose_folder/)
  assert.match(source, /revealDirectoryMutation\.mutate\(project\.root_path\)/)
  assert.match(menuSource, /projects\.action\.reveal/)
  assert.doesNotMatch(source, /安全关闭|closeCurrentProject/)
})

test('new project dialogs prefer YOLO creation every time they open', () => {
  const source = readFileSync(new URL('./HomePage.jsx', import.meta.url), 'utf8')
  const styles = readFileSync(new URL('../styles/projects.sass', import.meta.url), 'utf8')
  assert.match(source, /const \[createMode, setCreateMode\] = useState\('yolo'\)/)
  assert.match(source, /const openCreateDialog = \(\) => \{ setActionError\(null\); resetCreationFields\(\); setCreateMode\('yolo'\); setDialog\('create'\) \}/)
  assert.match(source, /<Modal className="project-create-dialog" title=\{t\('projects\.dialog\.create\.title'\)\}/)
  assert.match(source, /<LumiDialog className=\{className\}/)
  assert.match(styles, /\.lumi-dialog\.project-create-dialog\n\s+width: min\(820px, calc\(100vw - 32px\)\)/)
  assert.match(source, /<PictureBookProfileFields value=\{pictureBookDraft\}/)
  assert.match(source, /await preflightImageGeneration\(pictureBook\)[\s\S]*await createProject/)
})

test('YOLO creation prioritizes its name and story idea and validates on submit', () => {
  const source = readFileSync(new URL('./HomePage.jsx', import.meta.url), 'utf8')
  const priorityFields = source.match(/<div className="project-create-priority-fields">([\s\S]*?)<\/div>\n          <div className="project-dialog-field">/)
  assert.ok(priorityFields)
  assert.match(priorityFields[1], /projects\.field\.name/)
  assert.match(priorityFields[1], /projects\.field\.story_idea/)
  assert.match(source, /className="project-dialog-form" noValidate onSubmit=\{submitCreateForm\}/)
  assert.match(source, /const errors = projectCreationErrors/)
  assert.match(source, /<button type="submit" disabled=\{pending\}>/)
  assert.doesNotMatch(source, /disabled=\{pending \|\| projectDefaultsQuery\.isPending/)
})

test('both creation modes use a collapsed editable overall style initialized from server defaults', () => {
  const source = readFileSync(new URL('./HomePage.jsx', import.meta.url), 'utf8')
  assert.match(source, /default_overall_styles/)
  assert.match(source, /<details ref=\{overallStyleDetailsRef\} className="project-overall-style">/)
  assert.doesNotMatch(source, /<details[^>]*project-overall-style[^>]*\sopen(?:=|\s|>)/)
  assert.match(source, /projects\.field\.overall_style_default/)
  assert.match(source, /projects\.field\.overall_style_custom/)
  assert.match(source, /setOverallStyleDirty\(true\)/)
  assert.match(source, /setOverallStyle\(defaultOverallStyle\); setOverallStyleDirty\(false\)/)
  assert.match(source, /createProject\(\{ name, parentPath, generationLanguage, pictureBook, overallStyle \}\)/)
  assert.match(source, /createMutation\.mutate\(\{ name, parentPath, generationLanguage, pictureBook, overallStyle \}\)/)
})

test('home conversation composer preserves input, retry identity, and public navigation targets', () => {
  const source = readFileSync(new URL('./HomePage.jsx', import.meta.url), 'utf8')
  const api = readFileSync(new URL('../api/projects.js', import.meta.url), 'utf8')
  assert.match(source, /<textarea id="project-creation-input"[^>]*value=\{creationInput\}/)
  assert.match(source, /if \(!creationInput\.trim\(\)\) return/)
  assert.match(source, /creationMutation\.mutate\(\{ inputText: creationInput, idempotencyKey: checkpoint\.idempotencyKey, referenceFiles:/)
  assert.match(source, /creationCheckpoint\?\.inputText === creationInput/)
  assert.match(source, /window\.sessionStorage\.setItem\(CREATION_CHECKPOINT_KEY/)
  assert.match(source, /disabled=\{creationPending \|\| !creationInput\.trim\(\)/)
  assert.match(source, /const creationPending = creationMutation\.isPending/)
  assert.match(source, /creationSession\?\.status === 'failed'/)
  assert.match(source, /creationError \? <div className="project-creation-composer__failure"/)
  assert.match(source, /disabled=\{creationPending \|\| \(selectedCreationProject \? !creationInput\.trim\(\) : !creationCheckpoint\)\} onClick=\{retryCreation\}/)
  assert.match(source, /navigate\(`\/projects\/\$\{encodeURIComponent\(session\.project_uuid\)\}\?chat_thread_uuid=\$\{encodeURIComponent\(session\.thread_uuid\)\}`\)/)
  assert.match(source, /retryProjectCreationSession/)
  assert.match(api, /\/api\/v1\/project-creation-sessions/)
  assert.match(api, /input_text: inputText, idempotency_key: idempotencyKey/)
  assert.doesNotMatch(source, /projects\.conversation[\s\S]{0,600}parentPath/)
})

test('home conversation composer carries recoverable image references into the first turn', () => {
  const source = readFileSync(new URL('./HomePage.jsx', import.meta.url), 'utf8')
  const api = readFileSync(new URL('../api/projects.js', import.meta.url), 'utf8')
  const editor = readFileSync(new URL('../components/CreationReferenceEditor.jsx', import.meta.url), 'utf8')
  assert.match(source, /accept="image\/png,image\/jpeg,image\/webp"/)
  assert.match(source, /selectProjectChatImageFiles/)
  assert.match(source, /selectProjectChatClipboardImages/)
  assert.match(source, /<ReferenceStrip projectUuid=/)
  assert.match(source, /!selectedCreationProject \? <CreationReferenceEditor/)
  for (const field of ['reference_role', 'title', 'instruction', 'include_in_yolo']) assert.match(source, new RegExp(field))
  assert.match(source, /creationReferencesFromCheckpoint[\s\S]*referenceRole: reference\.reference_role[\s\S]*planTitle: reference\.title[\s\S]*instruction: reference\.instruction[\s\S]*includeInYolo: reference\.include_in_yolo/)
  assert.match(source, /serverReferenceFiles[\s\S]*reference_role: reference\.reference_role[\s\S]*include_in_yolo: reference\.include_in_yolo/)
  assert.match(editor, /const referenceRoles = \['auto', 'character', 'scene', 'prop', 'style'\]/)
  assert.match(editor, /aria-pressed=\{included\}/)
  assert.match(editor, /maxLength="160"/)
  assert.match(editor, /maxLength="2000"/)
  assert.match(source, /referenceFiles: checkpoint\.referenceFiles/)
  assert.match(source, /uploadProjectCreationReference\(session\.uuid, reference\.uuid, local\.file\)/)
  assert.match(source, /if \(session\.status === 'active'\) return session[\s\S]*if \(firstUploadError\) \{[\s\S]*getProjectCreationSession\(session\.uuid\)/)
  assert.match(source, /creationSession\?\.status === 'awaiting_references'/)
  assert.match(source, /creationReferencesFromCheckpoint\(loadCreationCheckpoint\(\)\)/)
  const lockedFill = source.match(/if \(refillLockedManifest\) \{([\s\S]*?)\n\s+return\n\s+\}/)
  assert.ok(lockedFill)
  assert.match(lockedFill[1], /return \{ \.\.\.reference, file, status: 'selected'/)
  assert.doesNotMatch(lockedFill[1], /filename: file\.name|mimeType: file\.type|byteSize: file\.size/)
  assert.match(api, /reference_files: referenceFiles/)
  assert.match(api, /references\/\$\{encodeURIComponent\(referenceUuid\)\}\/uploads/)
})

test('home conversation composer can publish into a selected project and open its new thread', () => {
  const source = readFileSync(new URL('./HomePage.jsx', import.meta.url), 'utf8')
  const styles = readFileSync(new URL('../styles/projects.sass', import.meta.url), 'utf8')
  assert.match(source, /className="project-creation-composer__context"[\s\S]*aria-haspopup="menu"/)
  assert.match(source, /selectableCreationProjects\.map\(\(project\) => <button[\s\S]*role="menuitemradio"/)
  assert.match(source, /createAssetUpload\(projectUuid,[\s\S]*finalizeAssetUpload\(projectUuid/)
  assert.match(source, /createChatThread\(projectUuid, \{ title: suggestedChatThreadTitle\(inputText\) \}\)/)
  assert.match(source, /createChatTurn\(projectUuid, thread\.uuid, \{ input_text: inputText, references: referenceInputs \}\)/)
  assert.match(source, /setCreationTargetThread\(\{ projectUuid, threadUuid: thread\.uuid \}\)/)
  assert.match(source, /navigate\(`\/projects\/\$\{encodeURIComponent\(projectUuid\)\}\?chat_thread_uuid=\$\{encodeURIComponent\(thread\.uuid\)\}`\)/)
  assert.match(styles, /\.project-creation-composer__context-menu[\s\S]*position: absolute/)
  assert.match(styles, /\[aria-expanded="true"\]:hover/)
  assert.match(styles, /\.project-creation-composer__context-menu[\s\S]*?&\[aria-checked="true"\]:hover[\s\S]*?color: \$color-text[\s\S]*?background: \$color-surface-muted/)
})
